### PR TITLE
feat: Install Laravel 7.0

### PR DESCRIPTION
**Pull request by digitlimit**
BREAKING CHANGE: Index.php now loads Laravel app

## Description
Laravel 7.0 was install
Dependencies:
- Laravel 7.0 
- PHP >= 7.2.5
- BCMath PHP Extension
- Ctype PHP Extension
- Fileinfo PHP extension
- JSON PHP Extension
- Mbstring PHP Extension
- OpenSSL PHP Extension
- PDO PHP Extension
- Tokenizer PHP Extension
- XML PHP Extension

Fixes #(issue 25) #(#25 )

## How Has This Been Tested?
Run `phpunit` in the root of the application

image

image

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have added necessary inline code documentation
- [x] I have added tests that prove my fix is effective and that this feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by codergab — APPROVED** [review]
All good to go.

**Review by dolad — APPROVED** [review]
Good to go

**Comment by jayumaks** [comment]
All good sir

**Review by jayumaks — APPROVED** [review]
good to go sir

**Pull request merged**
