### PR TITLE
ft: laravel table seeders

### LINKED ISSUE #28: Create Laravel Table seeders
**Is your feature request related to a problem? Please describe.**
Create Laravel Table seeders

Issue PR #38

### PR DESCRIPTION
**Pull request by digitlimit**
ft: laravel table seeders

Add laravel table seeders for testing

Fixes: #28

### CODE REVIEW

**Review by dolad — APPROVED** [review]

**Comment by dolad** [comment]
welldone

**Review by dolad — APPROVED** [review]

**Comment by dolad** [comment]
Good to go

**Review by codergab — APPROVED** [review]
All good.

**Review by jayumaks — APPROVED** [review]
good boss

**Pull request merged**
