### PR TITLE
feat:create laravel migration

### LINKED ISSUE #27: Create Laravel Migrations
**Is your feature request related to a problem? Please describe.**
Create Laravel Migrations for tables

### PR DESCRIPTION
**Pull request by dolad**
ft: create laravel migration

Adding all migration to the develop branch

Fixes #27

### CODE REVIEW

**Comment by dolad** [comment]
feat: create laravel migrations
Adding all migrations on Develop branch
Fixes: #36

**Review by codergab — APPROVED** [review]
All good.

**Review by jayumaks — APPROVED** [review]
OK SIR

**Review by digitlimit — APPROVED** [review]
Good

**Pull request merged**
